appname = TravelSphere-Mojammel
httpport = 8080
runmode = dev

sessionon = true
sessioname = travelsphere_session

wishlist_store_path = data/wishlist.json

restcountries_base_url = https://restcountries.com/v3.1
opentripmap_base_url   = https://api.opentripmap.com/0.1/en/places

opentripmap_api_key = WILL_ADD
